SELECT
  workflow_uuid,
  status,
  name,
  application_version,
  application_id,
  executor_id,
  queue_name,
  priority,
  authenticated_user,
  assumed_role,
  authenticated_roles,
  inputs,
  output,
  error,
  created_at,
  updated_at,
  to_timestamp(created_at / 1000.0) AS created_ts,
  to_timestamp(updated_at / 1000.0) AS updated_ts,
  workflow_timeout_ms,
  workflow_deadline_epoch_ms,
  started_at_epoch_ms,
  recovery_attempts,
  queue_partition_key,
  deduplication_id,
  forked_from,
  owner_xid
FROM dbos.workflow_status
WHERE workflow_uuid = :uuid;
